ossf/glossary

- README.md
Add crosslink to Google docs document listing planned terms.
> Add crosslink to Google docs document listing planned terms

- content/en/integrity.md
> Add integrity

- content/en/confidentiality.md
> Add confidentiality

- content/en/cyber-resiliance-act.md
- wordlist.txt
> Add Cyber Resilience Act (CRA)

- content/en/cross-site-scripting.md
> Add Cross-site Scripting

- content/en/heap-overflow.md
> Add "heap overflow"

- .github/workflows/deploy-github-pages.yml
- config.toml
- content/en/cisa.md
- content/en/mitre.md
- content/en/nist.md
- wordlist.txt
Implements parts of the GitHub pages deployment workflow as described in this documentation https://www.docsy.dev/docs/deployment/#deployment-on-github-pages
- [x ] This PR does not contain plagiarism
- [x ] I have signed off on all commits 
> Configure gh pages

- content/en/cisa.md
- content/en/mitre.md
- content/en/nist.md
Add files for CISA, MITRE and NIST
n/a
- [ x] This PR does not contain plagiarism
> Add organizations to glossary

- content/en/hardening.md
> Add hardening

- content/en/exfiltration.md
- wordlist.txt
> Add Exfiltration

- .gitignore
- package-lock.json
- themes/docsy/assets/vendor/bootstrap/package-lock.json
- themes/docsy/userguide/package-lock.json
Attempting to resolve GH pages build errors by removing package-lock.json from .gitignore per https://github.com/actions/setup-node/issues/694 
> Removes package-lock.json from .gitignore and adds 3 package-lock files

- CODEOWNERS
- CONTRIBUTING.md
- LOCALIZATION.md
- code-of-conduct.md
- config.toml
- glossary.md
- spin-new-glossary.md
This is an update to a batch of files from spinning a copy of CNCF Glossary, replacing CNCF references to OpenSSF information.
> Update several files to replace CNCF references

- config.toml
> Revert "Update config.toml"

- .github/workflows/deploy-github-pages.yml
Updating some of the settings in the workflow file in an attempt to fix the styling after introducing the custom subdomain.
> Update deploy-github-pages.yml for deploy branch and baseurl

- content/en/fuzzing.md
> Add fuzzing

- content/en/negative-testing.md
> Add Negative Testing

- content/en/reproducible-build.md
> Add reproducible builds

- content/en/null-pointer-dereference.md
- wordlist.txt
> Add NULL Pointer Dereference

- content/en/object-code.md
- content/en/source-code.md
> Add "source code"

- config.toml
- content/en/search.md
Adds the missing search page and enables offline JS search
Resolves #38 
> Fix search

- .github/workflows/deploy-github-pages.yml
Add trailing slash to base URL on deployment config
> Add trailing slash to base URL on deployment config
